# Generated by Django 3.2.8 on 2021-11-02 03:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodel',
            name='field1',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='dbmodel',
            name='intfield',
            field=models.IntegerField(default=1),
        ),
    ]
